import Head from 'next/head'
import Footer from './Footer/Footer'
import Navbar from './Navbar/Navbar'

export const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div>
                <Navbar />
                <div className="">
                    <div className="">{children}</div>
                </div>
                <Footer />
            </div>
        </>
    )
}